### ISSUE TITLE
Does not work w/ jQuery 1.8.3

### ISSUE THREAD

**Issue by soulseekah** [pressjitsu/pageviews#10]
`.ajax( method` was introduced in 1.9.0+

**Comment by soulseekah** [comment]
https://wordpress.org/support/topic/plugin-does-not-display-view-numbers/#post-13533389

**Comment by mihdan** [comment]
This issue is no longer needed. Kernel jQuery version updated

**Comment by soulseekah** [comment]
Thanks.
