### ISSUE TITLE
Get views by post ID

### ISSUE THREAD

**Issue by vburlak** [pressjitsu/pageviews#2]
Hi @pressjitsu
Thanks for the great plugin. It's works very well.

Have some questions about plugin: 
1. Do you plan implement action to display the page / post views by post id (outside of the loop)?
2. And it would be great to have the ability to sync page views with your server locally( maybe once a week), to have access to the local variables for tasks, such as sorting posts by number of post views. Or maybe you have some ideas how to implement it?

**Comment by pj-dave** [comment]
Hi there! Thank you for getting in touch.

We do have endpoints available on pv.pjtsu.com which you can query manually if you like, but note that there's soft and hard rate-limiting when querying from the same IP address, so please cache the results for a few minutes at least.

We are working on some extensions to display popular posts and other things, including importers or sync-ers from other plugins and services. We'll announce the availability/betas on [our blog](https://pressjitsu.com/blog/) when they're live. In the meantime, you can query multiple posts with the v1/get endpoint and perhaps cache them in the post metadata.

Hope that helps.
