### ISSUE TITLE
Terms of Use and Privacy Policy - pv.pjtsu.com

### ISSUE THREAD

**Issue by vburlak** [pressjitsu/pageviews#3]
Hi @pressjitsu. 
I can't find any information about TOS and Privacy Policy for https://pv.pjtsu.com
It will be great to read more about it

**Comment by pj-dave** [comment]
Thanks @vburlak, we currently don't have any official docs covering terms of service and privacy policy for the pv.pjtsu.com service domain, but it's on our list to create them.

In general, you're free to use the counter service as you please, with or without WordPress. If you have a website generating more than 10M pageviews per month, we recommend getting in touch with us via e-mail as you may be hitting our rate limiting on API requests. As for privacy:

* We collect and store the initial registration request (including your website's IP address and UA string, often containing your WordPress version) – in return you receive (and store in `wp_options`) an account key and account key secret, which then allow you to query other endpoints of the API.
* We collect and store for a limited time (aggregations for up to 7 days, raw logs for up to 52 weeks) all request logs to the pv.pjtsu.com domain, including referrer headers and IP addresses. These are used to track and debug the service usage, find patterns of abuse, as well as scale the service.
* We collect and store the counter keys provided by the API client (usually post IDs, but in custom implementations could also be more meaningful strings, such as `tag-archive` or `search`), as well as the numeric counter values (given with the `v1/set` endpoint).

If you have any more specific questions, or wish your data to be purged from our logs and database immediately, please feel free to reach out to us via e-mail (support@pressjitsu.com) and provide your account key and account secret strings (`wp option get pageviews_config`).

Hope that helps!

**Comment by soulseekah** [comment]
Privacy policy available here https://pageviews.io/privacy/
Terms of use available here https://pageviews.io/tos/
