### ISSUE TITLE
Rounding numbers & unit

### ISSUE THREAD

**Issue by financeforgeek** [pressjitsu/pageviews#4]
Hello @pressjitsu!

I’d like to know if there is a simple way to modify pageviews.js in order to change how numbers are displayed. Ideally I’d like to have the number divided by 1000 and then add a K to it. For example, if I have 50,000 views I’d like to transform it to 50k.
Any ideas what I’d have to modify in the .js ? I’m well aware that this would be lost after an update of course, hence I'm asking here, because if it's complicated this would be a nice feature to add :)

**Comment by soulseekah** [comment]
There's no flexible way to do this right now, we'll think about introducing some sort of callback there.

In the meantime you can patch the `text` calls at https://github.com/pressjitsu/pageviews/blob/master/pageviews.js#L37 and https://github.com/pressjitsu/pageviews/blob/master/pageviews.js#L56

Chain your own rounding function there. For example (line 56): `el.text(e[i]);` would become `el.text(roundme(e[i]));` and your `roundme` function would divide by 1000 and add the 'K'. Should be easy.

Let us know how it goes. And, yes, you will lose these changes after the next update of pageviews for WordPress is released. It will, hopefully, contain a callback then.

**Comment by financeforgeek** [comment]
Thanks a lot for the quick reply! I'll try to add this, I'm not really at ease with Javascript yet, I'll let you know how it goes :)

**Comment by financeforgeek** [comment]
Ok got it working! As you advised I added a function roundme which did the trick 👍

function roundme(num) {
		if (num >= 1000000) {
        return (num / 1000000).toFixed(1).replace(/\.0$/, '') + 'M'; }
		if (num >= 1000) {
        return (num / 1000).toFixed(1).replace(/\.0$/, '') + 'K'; }
		return num;	}

And then I replaced both occurence of text(e[i]) with text (roundme(e[i]))

Thanks!

**Comment by soulseekah** [comment]
Glad to hear it worked :) Stay tuned for a better way to dot this by registering a callback function. Reopening for internal feature request tracking purposes.

**Comment by akyritsis** [comment]
@soulseekah I tried to do the same, but it doesn't seem to have any effect on my website pcsteps.gr

This is my pagevies.js file:

https://pastebin.com/QNrsVJxk

It seems pretty straightforward, but my javascript knowledge is spotty at best. Have I done something wrong?

**Comment by soulseekah** [comment]
Fixed in https://github.com/pressjitsu/pageviews/commit/098db20c797a1e3f1561b3583e6e22ec120e7e7a

Usage:

```
add_action( 'pageviews_before_js', function() {
    ?>
    _pv_config.output_filter = function(v) { return "test " + v; };
    <?php
}
```
