### ISSUE TITLE
Increase counting x2 automatically

### ISSUE THREAD

**Issue by zauradigozalov** [pressjitsu/pageviews#5]
Hi,

Could you please advise how to automatically increase counting x2 automatically. For Example on 3 time refreshing of website counter=counter+2

Thanks

**Comment by soulseekah** [comment]
Hi there.

You can manually trigger the 'pageviews-update' JavaScript event against the body a second time. It will increase the counter once more.

**Comment by zauradigozalov** [comment]
Sorry but I'm new in javascript. Could you please send a solution for this?

**Comment by soulseekah** [comment]
`jQuery(document).trigger('pageviews-update');`

**Comment by zauradigozalov** [comment]
Thank you very much, it works !

**Comment by soulseekah** [comment]
Glad to hear it works. Can I ask why you're doing this, though? :)

**Comment by zauradigozalov** [comment]
Actually some post authors needs to increase post views. Sometimes fake actions is the best way :)
