### ISSUE TITLE
Скрипты плагина не поддаются минимизации и конкатенации кешируюшими плагинами

### ISSUE THREAD

**Issue by mihdan** [pressjitsu/pageviews#7]
Так как подключение скриптов у вас [реализовано](https://github.com/pressjitsu/pageviews/blob/master/pageviews.php#L136) на хуке `wp_footer`, то большинство кеширующих плагинов не могут минимизировать и приклеить к другим скриптам ваш pageviews.js. И нет возвожности убрать `?v=` из пути.

Тут либо вешать все на стандартный хук `wp_enqueue_script` либо класть с плагином минимизированную версию скрипта и подключать `pageviews.js` или `pageviews.min.js` в зависимости от `SCRIPT_DEBUG`.

**Comment by mihdan** [comment]
Добавил PR, решающий половину вопроса https://github.com/pressjitsu/pageviews/pull/8

**Comment by soulseekah** [comment]
= 0.11.0 =
* Added pageviews_script_version_param filter to remove JS version fragment
* Added minification. Enjoy your pagespeeds.

**Comment by mihdan** [comment]
@soulseekah на wp.org то задеплоишь?
